server:
  port: 8761  # Puerto estándar para Eureka Server
eureka:
  client:
    register-with-eureka: false  # El propio servidor no se registra
    fetch-registry: false  # No necesita obtener el registro de otros servidores
  server:
    enable-self-preservation: false  # Desactiva la autopreservación para desarrollo
spring:
  application:
    name: eureka-server  # Nombre del servicio de Eureka
